### ISSUE TITLE
GamesDataController/getGames ERROR

### ISSUE THREAD

**Issue by WarezAddict-com** [sergeivl/fileprofit-client#1]
```
turbo@Linux-Desktop:/torrent/fileprofit-client$ php public/index.php GamesDataController/getGames
```

```
...
...
...
< HTTP/1.1 200 OK
< Server: nginx
< Date: Sun, 25 Mar 2018 04:43:00 GMT
< Content-Type: application/x-bittorrent
< Content-Length: 23873
< Connection: keep-alive
< Keep-Alive: timeout=60
< Last-Modified: Thu, 24 Sep 2015 08:20:08 GMT
< ETag: "c10e0-5d41-52079e626fe00"
< Accept-Ranges: bytes
< 
* Curl_http_done: called premature == 0
* Connection #0 to host putingamer.net left intact
[2018-03-25 00:43:00] cli_logger.INFO: 370) sniper-elite-3 [] []
* Hostname putingamer.net was found in DNS cache
*   Trying 195.245.113.205...
* TCP_NODELAY set
* Connected to putingamer.net (195.245.113.205) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* NPN, negotiated HTTP1.1
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=putingamer.net
*  start date: Feb 21 02:55:22 2018 GMT
*  expire date: May 22 02:55:22 2018 GMT
*  subjectAltName: host "putingamer.net" matched cert's "putingamer.net"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET /wp-content/uploads/2015/09/GRID-Autosport.jpe HTTP/1.1
Host: putingamer.net
User-Agent: GuzzleHttp/6.2.1 curl/7.52.1 PHP/7.0.27-0+deb9u1

< HTTP/1.1 200 OK
< Server: nginx
< Date: Sun, 25 Mar 2018 04:43:01 GMT
< Content-Type: image/jpeg
< Content-Length: 56031
< Connection: keep-alive
< Keep-Alive: timeout=60
< Last-Modified: Wed, 02 Dec 2015 18:29:36 GMT
< ETag: "c0d21-dadf-525ee74d34400"
< Accept-Ranges: bytes
< 
* Curl_http_done: called premature == 0
* Connection #0 to host putingamer.net left intact
PHP Fatal error:  Uncaught Intervention\Image\Exception\NotSupportedException: Encoding format (jpe) is not supported. in /torrent/fileprofit-client/vendor/intervention/image/src/Intervention/Image/AbstractEncoder.php:163
Stack trace:
#0 /torrent/fileprofit-client/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(77): Intervention\Image\AbstractEncoder->process(Object(Intervention\Image\Image), 'jpe', NULL)
#1 /torrent/fileprofit-client/vendor/intervention/image/src/Intervention/Image/Image.php(119): Intervention\Image\AbstractDriver->encode(Object(Intervention\Image\Image), 'jpe', NULL)
#2 /torrent/fileprofit-client/vendor/intervention/image/src/Intervention/Image/Image.php(139): Intervention\Image\Image->encode('jpe', NULL)
#3 /torrent/fileprofit-client/app/services/GamesSaveService.php(179): Intervention\Image\Image->save('/torrent/filepr..')
#4 /torrent/fileprofit-client/app/services/GamesSaveService.php(166): App\Services\GamesSaveService->uniquelyImg('/torrent/filepr...')
#5 /torrent/fileprofit-client/app/services/GamesSaveService.php(60): App\Services\GamesSaveService->saveCover(Object(App\Models\Game), Array)
#6 /torrent/fileprofit-client/app/console/GamesDataController.php(26): App\Services\GamesSaveService->saveAllGames()
#7 /torrent/fileprofit-client/bootstrap/router.php(17): App\Console\GamesDataController->getGames()
#8 /torrent/fileprofit-client/bootstrap/app.php(11): require_once('/torrent/filepr...')
#9 /torrent/fileprofit-client/public/index.php(10): require_once('/torrent/filepr...')
#10 {main}
  thrown in /torrent/fileprofit-client/vendor/intervention/image/src/Intervention/Image/AbstractEncoder.php on line 163
```

Sorry, I would fix this for you if I knew how, but I'm not much of a coder!

Google Translate: Извините, я исправлю это для вас, если бы знал, как, но я не очень кодер!

**Comment by sergeivl** [comment]
The problem is resolved
